apiVersion: v1
kind: List
metadata:
  name: sample-app-list-1
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: azure-app-1
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: azure-app-1
      namespace: azure-app-1
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: restricted-scc-use
      namespace: azure-app-1
    rules:
      - apiGroups:
          - security.openshift.io
        resourceNames:
          - restricted
        resources:
          - securitycontextconstraints
        verbs:
          - use
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: restricted-scc-use
      namespace: azure-app-1
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: restricted-scc-use
    subjects:
      - kind: ServiceAccount
        name: azure-app-1
        namespace: azure-app-1
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: azure-app-1
      name: azure-app-1
      namespace: azure-app-1
    spec:
      ports:
        - port: 80
          protocol: TCP
          targetPort: 20000
      selector:
        app: azure-app-1
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: azure-app-1
      namespace: azure-app-1
    spec:
      port:
        targetPort: 20000
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: azure-app-1
        weight: 100
      wildcardPolicy: None
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: azure-app-1
      name: azure-app-1
      namespace: azure-app-1
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: azure-app-1
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
        type: RollingUpdate
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: azure-app-1
        spec:
          serviceAccount: azure-app-1
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - azure-app-1
                  topologyKey: kubernetes.io/hostname
          containers:
            - image: "${PIPELINE_IMAGE_URL}"
              name: azure-app-1
              command: [ "./bin/main"]
              resources:
                requests:
                  cpu: 10m
                  memory: 10M
              ports:
                - containerPort: 20000
